name: Deployment-of-python-app

on:
  push:
    paths:
      - 'test**'
    branches:
      - 'feature/pipelines'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print event
      run: echo "this has been triggered ${{ github.event_name }} event"
    - name: Print os
      run: echo "This job is running on ${{ runner.os }} server hosted on github!"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
        pip install pytest
    - name: Run tests
      run: pytest test*
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Style Check
      run: |
        pip install pycodestyle
        pycodestyle *.py 
    - name: Build container
      run: |
        echo "Building a container image..."
        sleep 10
    - name: Deploy to cluster
      run: |
        echo "Deploying to cluster..."
        sleep 10
        echo "Container has been deployed!"
    - name: Job status
      run: echo "This job's status is ${{ job.status }}."